"""empty message

Revision ID: 07e4900de360
Revises: a6757cabcd99
Create Date: 2025-03-21 13:02:51.171499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07e4900de360'
down_revision: Union[str, None] = 'a6757cabcd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_checker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_date', sa.Date(), nullable=False),
    sa.Column('execute_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_date_checker'))
    )
    op.add_column('bills', sa.Column('bill_no', sa.Integer(), nullable=False))
    op.add_column('bills', sa.Column('bill_title', sa.String(length=255), nullable=False))
    op.add_column('bills', sa.Column('bill_title_eng', sa.String(length=255), nullable=True))
    op.add_column('bills', sa.Column('bill_body', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('bill_body_eng', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('ppsr_name', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('ppsl_date', sa.Date(), nullable=True))
    op.add_column('bills', sa.Column('jrcmit_name', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('rgs_rsln_date', sa.Date(), nullable=True))
    op.add_column('bills', sa.Column('rgs_rsln_rslt', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('bill_url', sa.String(length=500), nullable=True))
    op.drop_column('bills', 'url')
    op.drop_column('bills', 'title_eng')
    op.drop_column('bills', 'date')
    op.drop_column('bills', 'title')
    op.drop_column('bills', 'body_eng')
    op.drop_column('bills', 'body')
    op.drop_column('bills', 'num')
    op.alter_column('user_page_visits', 'visit_time',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_page_visits', 'visit_time',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.add_column('bills', sa.Column('num', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('body', mysql.TEXT(), nullable=True))
    op.add_column('bills', sa.Column('body_eng', mysql.TEXT(), nullable=True))
    op.add_column('bills', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('bills', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('bills', sa.Column('title_eng', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bills', sa.Column('url', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('bills', 'bill_url')
    op.drop_column('bills', 'rgs_rsln_rslt')
    op.drop_column('bills', 'rgs_rsln_date')
    op.drop_column('bills', 'jrcmit_name')
    op.drop_column('bills', 'ppsl_date')
    op.drop_column('bills', 'ppsr_name')
    op.drop_column('bills', 'bill_body_eng')
    op.drop_column('bills', 'bill_body')
    op.drop_column('bills', 'bill_title_eng')
    op.drop_column('bills', 'bill_title')
    op.drop_column('bills', 'bill_no')
    op.drop_table('date_checker')
    # ### end Alembic commands ###
