"""Change BillRecommendation table to SimilarityScore

Revision ID: 0d70ddbcd808
Revises: 656b41a11374
Create Date: 2025-02-24 21:57:45.221088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "0d70ddbcd808"
down_revision: Union[str, None] = "656b41a11374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the 'role' table already exists before creating it
    result = op.get_bind().execute(text("SHOW TABLES LIKE 'role';"))
    if not result.fetchone():
        op.create_table(
            "role",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("role", sa.String(length=10), nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        )
    op.create_table(
        "similarity_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_bill_no", sa.String(length=255), nullable=False),
        sa.Column("target_bill_no", sa.String(length=255), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_scores")),
        sa.UniqueConstraint(
            "source_bill_no", "target_bill_no", name="uq_source_target"
        ),
    )
    op.create_table(
        "user_interests",
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "interest_id", "user_id", name=op.f("pk_user_interests")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.drop_table("bill_recommendations")
    op.drop_table("INTEREST")
    op.drop_table("USER")
    op.drop_table("ROLE")
    op.drop_table("USER_INTEREST")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER_INTEREST",
        sa.Column("interest_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("interest_id", "user_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "ROLE",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("role", mysql.VARCHAR(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "USER",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("gender", mysql.VARCHAR(length=10), nullable=True),
        sa.Column("address", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("age", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("email", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("role_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "INTEREST",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("keyword", mysql.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "bill_recommendations",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_bill_no", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("recommended_bill_no", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("similarity_score", mysql.FLOAT(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("users")
    op.drop_table("user_interests")
    op.drop_table("similarity_scores")
    op.drop_table("role")
    # ### end Alembic commands ###
