"""empty message

Revision ID: 15bd9cc68f89
Revises: 
Create Date: 2025-02-12 23:11:28.139050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bd9cc68f89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ord_num', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('keyword1', sa.String(length=500), nullable=True),
    sa.Column('keyword2', sa.String(length=500), nullable=True),
    sa.Column('keyword3', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill')),
    sa.UniqueConstraint('bill_id', name=op.f('uq_bill_bill_id'))
    )
    op.create_table('conf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ord_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conf'))
    )
    op.create_table('bill_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('conf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], name=op.f('fk_bill_summary_bill_summary_bill_id_bill')),
    sa.ForeignKeyConstraint(['conf_id'], ['conf.id'], name=op.f('fk_bill_summary_bill_summary_conf_id_conf')),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_bill_summary'))
    )
    op.create_table('conf_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('conf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conf_id'], ['conf.id'], name=op.f('fk_conf_summary_conf_summary_conf_id_conf')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conf_summary'))
    )
    op.create_table('bill_summary_relation',
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], name=op.f('fk_bill_summary_relation_bill_summary_relation_bill_id_bill')),
    sa.ForeignKeyConstraint(['summary_id'], ['bill_summary.summary_id'], name=op.f('fk_bill_summary_relation_bill_summary_relation_summary_id_bill_summary')),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_bill_summary_relation'))
    )
    op.create_table('conf_summary_relation',
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conf_id'], ['conf.id'], name=op.f('fk_conf_summary_relation_conf_summary_relation_conf_id_conf')),
    sa.ForeignKeyConstraint(['summary_id'], ['conf_summary.id'], name=op.f('fk_conf_summary_relation_conf_summary_relation_summary_id_conf_summary')),
    sa.PrimaryKeyConstraint('conf_id', 'summary_id', name=op.f('pk_conf_summary_relation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conf_summary_relation')
    op.drop_table('bill_summary_relation')
    op.drop_table('conf_summary')
    op.drop_table('bill_summary')
    op.drop_table('conf')
    op.drop_table('bill')
    # ### end Alembic commands ###
