"""Like type

Revision ID: 29645b67b437
Revises: 4a993fa9a76e
Create Date: 2025-04-11 13:54:30.808931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29645b67b437'
down_revision: Union[str, None] = '4a993fa9a76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like_type', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like_type')
    # ### end Alembic commands ###
