"""grammar fix

Revision ID: 300072a4706a
Revises: 71fe1ab14751
Create Date: 2025-03-12 20:52:46.609899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "300072a4706a"
down_revision: Union[str, None] = "71fe1ab14751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bills", sa.Column("ppsr_name", sa.String(length=100), nullable=True))
    op.drop_column("bills", "ppsl_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills", sa.Column("ppsl_name", mysql.VARCHAR(length=100), nullable=True)
    )
    op.drop_column("bills", "ppsr_name")
    ### end Alembic commands ###
