"""empty message

Revision ID: 5324e50d3b09
Revises: 
Create Date: 2025-02-14 22:40:44.262344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5324e50d3b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ord_num', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('keyword1', sa.String(length=500), nullable=True),
    sa.Column('keyword2', sa.String(length=500), nullable=True),
    sa.Column('keyword3', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills')),
    sa.UniqueConstraint('bill_id', name=op.f('uq_bills_bill_id'))
    )
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ord_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conferences'))
    )
    op.create_table('bill_summaries',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('conf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], name=op.f('fk_bill_summaries_bill_summaries_bill_id_bills')),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], name=op.f('fk_bill_summaries_bill_summaries_conf_id_conferences')),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_bill_summaries'))
    )
    op.create_table('conf_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('conf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], name=op.f('fk_conf_summaries_conf_summaries_conf_id_conferences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conf_summaries'))
    )
    op.create_table('bill_summary_relation',
    sa.Column('bill_id', sa.String(length=255), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], name=op.f('fk_bill_summary_relation_bill_summary_relation_bill_id_bills')),
    sa.ForeignKeyConstraint(['summary_id'], ['bill_summaries.summary_id'], name=op.f('fk_bill_summary_relation_bill_summary_relation_summary_id_bill_summaries')),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_bill_summary_relation'))
    )
    op.create_table('conf_summary_relation',
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], name=op.f('fk_conf_summary_relation_conf_summary_relation_conf_id_conferences')),
    sa.ForeignKeyConstraint(['summary_id'], ['conf_summaries.id'], name=op.f('fk_conf_summary_relation_conf_summary_relation_summary_id_conf_summaries')),
    sa.PrimaryKeyConstraint('conf_id', 'summary_id', name=op.f('pk_conf_summary_relation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conf_summary_relation')
    op.drop_table('bill_summary_relation')
    op.drop_table('conf_summaries')
    op.drop_table('bill_summaries')
    op.drop_table('conferences')
    op.drop_table('bills')
    # ### end Alembic commands ###
