"""add postal code and address_detail

Revision ID: 59e5ee7ad2c5
Revises: f410c0a2aa17
Create Date: 2025-03-29 16:04:37.036212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e5ee7ad2c5'
down_revision: Union[str, None] = 'f410c0a2aa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('address_detail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address_detail')
    op.drop_column('users', 'postal_code')
    # ### end Alembic commands ###
