"""add title for content

Revision ID: 5d32e4f1b75a
Revises: 7eac939fa813
Create Date: 2025-05-02 12:43:44.345981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d32e4f1b75a'
down_revision: Union[str, None] = '7eac939fa813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('title', sa.String(length=255), nullable=False))
    
    # Content 테이블에서 content_id 항목으로 Bill 테이블에서 bill_title 찾아서 입력
    connection = op.get_bind()
    contents = connection.execute(sa.text("SELECT id, content_id FROM contents")).fetchall()
    
    for content in contents:
        content_id = content[1]
        # content_id가 bill_id와 동일하다고 가정
        bill = connection.execute(
            sa.text("SELECT bill_title FROM bills WHERE bill_id = :bill_id"),
            {"bill_id": content_id}
        ).fetchone()
        
        if bill:
            connection.execute(
                sa.text("UPDATE contents SET title = :title WHERE id = :id"),
                {"title": bill[0], "id": content[0]}
            )
    
    op.alter_column('user_page_visits', 'visit_time',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_page_visits', 'visit_time',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_column('contents', 'title')
    # ### end Alembic commands ###
