"""add english columns

Revision ID: 69c25957eb9e
Revises: c3506f0b9f9e
Create Date: 2025-02-28 21:26:15.408168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c25957eb9e'
down_revision: Union[str, None] = 'c3506f0b9f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('title_eng', sa.String(length=255), nullable=False))
    op.add_column('bills', sa.Column('body_eng', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'body_eng')
    op.drop_column('bills', 'title_eng')
    # ### end Alembic commands ###
