"""change bills schema

Revision ID: 71fe1ab14751
Revises: a6757cabcd99
Create Date: 2025-03-12 20:43:40.682256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71fe1ab14751"
down_revision: Union[str, None] = "a6757cabcd99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bill_id", sa.String(length=255), nullable=True),
        sa.Column("bill_no", sa.Integer(), nullable=False),
        sa.Column("bill_title", sa.String(length=255), nullable=False),
        sa.Column("bill_title_eng", sa.String(length=255), nullable=True),
        sa.Column("bill_body", sa.Text(), nullable=True),
        sa.Column("bill_body_eng", sa.Text(), nullable=True),
        sa.Column("ppsl_name", sa.String(length=100), nullable=True),
        sa.Column("ppsl_date", sa.Date(), nullable=False),
        sa.Column("jrcmit_name", sa.String(length=100), nullable=True),
        sa.Column("rgs_rsln_date", sa.Date(), nullable=True),
        sa.Column("rgs_rsln_rslt", sa.String(length=100), nullable=True),
        sa.Column("ord_num", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=500), nullable=True),
        sa.Column("keyword1", sa.String(length=500), nullable=True),
        sa.Column("keyword2", sa.String(length=500), nullable=True),
        sa.Column("keyword3", sa.String(length=500), nullable=True),
        sa.Column("bill_url", sa.String(length=500), nullable=False),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills")),
        sa.UniqueConstraint("bill_id", name=op.f("uq_bills_bill_id")),
    )
    op.drop_index(
        "fk_bill_summaries_bill_summaries_bill_id_bills", table_name="bill_summaries"
    )
    op.drop_index(
        "fk_bill_summaries_bill_summaries_conf_id_conferences",
        table_name="bill_summaries",
    )
    op.create_foreign_key(
        op.f("fk_bill_summaries_bill_summaries_bill_id_bills"),
        "bill_summaries",
        "bills",
        ["bill_id"],
        ["bill_id"],
    )
    op.create_foreign_key(
        op.f("fk_bill_summaries_bill_summaries_conf_id_conferences"),
        "bill_summaries",
        "conferences",
        ["conf_id"],
        ["id"],
    )
    op.drop_index(
        "fk_bill_summary_relation_bill_summary_relation_bill_id_bills",
        table_name="bill_summary_relation",
    )
    op.create_foreign_key(
        op.f("fk_bill_summary_relation_bill_summary_relation_bill_id_bills"),
        "bill_summary_relation",
        "bills",
        ["bill_id"],
        ["bill_id"],
    )
    op.create_foreign_key(
        op.f(
            "fk_bill_summary_relation_bill_summary_relation_summary_id_bill_summaries"
        ),
        "bill_summary_relation",
        "bill_summaries",
        ["summary_id"],
        ["summary_id"],
    )
    op.drop_index(
        "fk_bills_embedding_bills_embedding_bill_id_bills", table_name="bills_embedding"
    )
    op.create_foreign_key(
        op.f("fk_bills_embedding_bills_embedding_bill_id_bills"),
        "bills_embedding",
        "bills",
        ["bill_id"],
        ["bill_id"],
    )
    op.drop_index(
        "fk_conf_summaries_conf_summaries_conf_id_conferences",
        table_name="conf_summaries",
    )
    op.create_foreign_key(
        op.f("fk_conf_summaries_conf_summaries_conf_id_conferences"),
        "conf_summaries",
        "conferences",
        ["conf_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_conf_summaries_conf_summaries_conf_id_conferences"),
        "conf_summaries",
        type_="foreignkey",
    )
    op.create_index(
        "fk_conf_summaries_conf_summaries_conf_id_conferences",
        "conf_summaries",
        ["conf_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_bills_embedding_bills_embedding_bill_id_bills"),
        "bills_embedding",
        type_="foreignkey",
    )
    op.create_index(
        "fk_bills_embedding_bills_embedding_bill_id_bills",
        "bills_embedding",
        ["bill_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f(
            "fk_bill_summary_relation_bill_summary_relation_summary_id_bill_summaries"
        ),
        "bill_summary_relation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_bill_summary_relation_bill_summary_relation_bill_id_bills"),
        "bill_summary_relation",
        type_="foreignkey",
    )
    op.create_index(
        "fk_bill_summary_relation_bill_summary_relation_bill_id_bills",
        "bill_summary_relation",
        ["bill_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_bill_summaries_bill_summaries_conf_id_conferences"),
        "bill_summaries",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_bill_summaries_bill_summaries_bill_id_bills"),
        "bill_summaries",
        type_="foreignkey",
    )
    op.create_index(
        "fk_bill_summaries_bill_summaries_conf_id_conferences",
        "bill_summaries",
        ["conf_id"],
        unique=False,
    )
    op.create_index(
        "fk_bill_summaries_bill_summaries_bill_id_bills",
        "bill_summaries",
        ["bill_id"],
        unique=False,
    )
    op.drop_table("bills")
    # ### end Alembic commands ###
