"""Change bill_no to bill_id

Revision ID: ab5543ff8246
Revises: bfbe2b49ae8a
Create Date: 2025-02-24 22:55:17.886083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5543ff8246'
down_revision: Union[str, None] = 'bfbe2b49ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_bill_id', sa.String(length=255), nullable=False),
    sa.Column('target_bill_id', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similarity_scores')),
    sa.UniqueConstraint('source_bill_id', 'target_bill_id', name='uq_source_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_scores')
    # ### end Alembic commands ###
