"""Change bill_no to bill_id

Revision ID: bfbe2b49ae8a
Revises: 0d70ddbcd808
Create Date: 2025-02-24 22:53:44.560365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfbe2b49ae8a"
down_revision: Union[str, None] = "0d70ddbcd808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("similarity_scores")
    op.create_table(
        "similarity_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_bill_id", sa.String(length=255), nullable=False),
        sa.Column("target_bill_id", sa.String(length=255), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_scores")),
        sa.UniqueConstraint(
            "source_bill_id", "target_bill_id", name="uq_source_target"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("similarity_scores")
    op.create_table(
        "similarity_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_bill_no", sa.String(length=255), nullable=False),
        sa.Column("target_bill_no", sa.String(length=255), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_scores")),
        sa.UniqueConstraint(
            "source_bill_no", "target_bill_no", name="uq_source_target"
        ),
    )
    # ### end Alembic commands ###
