"""Fix grammar error

Revision ID: c3506f0b9f9e
Revises: ab5543ff8246
Create Date: 2025-02-25 02:57:28.182679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3506f0b9f9e'
down_revision: Union[str, None] = 'ab5543ff8246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
