"""Add: BillsSimilarity table

Revision ID: ce0a18091c68
Revises: fc71d0511e74
Create Date: 2025-03-03 21:15:12.772164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce0a18091c68"
down_revision: Union[str, None] = "fc71d0511e74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills_similarity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bill_id", sa.String(length=255), nullable=False),
        sa.Column("similarity_bill_id", sa.String(length=255), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_similarity")),
        sa.UniqueConstraint(
            "bill_id", "similarity_bill_id", name=op.f("uq_bills_similarity_bill_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bills_similarity")
    # ### end Alembic commands ###
