"""empty message

Revision ID: ce8321c28e35
Revises: ca8a65ff8839
Create Date: 2025-03-03 22:21:10.415871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce8321c28e35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bill_id", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("title_eng", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_eng", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ord_num", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=500), nullable=True),
        sa.Column("keyword1", sa.String(length=500), nullable=True),
        sa.Column("keyword2", sa.String(length=500), nullable=True),
        sa.Column("keyword3", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills")),
        sa.UniqueConstraint("bill_id", name=op.f("uq_bills_bill_id")),
    )
    op.create_table(
        "conferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ord_num", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conferences")),
    )
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keyword", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interests")),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_table(
        "similarity_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_bill_id", sa.String(length=255), nullable=False),
        sa.Column("target_bill_id", sa.String(length=255), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_scores")),
        sa.UniqueConstraint(
            "source_bill_id", "target_bill_id", name="uq_source_target"
        ),
    )
    op.create_table(
        "user_interests",
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "interest_id", "user_id", name=op.f("pk_user_interests")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "bill_summaries",
        sa.Column("summary_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("bill_id", sa.String(length=255), nullable=True),
        sa.Column("conf_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.bill_id"],
            name=op.f("fk_bill_summaries_bill_summaries_bill_id_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["conf_id"],
            ["conferences.id"],
            name=op.f("fk_bill_summaries_bill_summaries_conf_id_conferences"),
        ),
        sa.PrimaryKeyConstraint("summary_id", name=op.f("pk_bill_summaries")),
    )
    op.create_table(
        "conf_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.Column("conf_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conf_id"],
            ["conferences.id"],
            name=op.f("fk_conf_summaries_conf_summaries_conf_id_conferences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conf_summaries")),
    )
    op.create_table(
        "bill_summary_relation",
        sa.Column("bill_id", sa.String(length=255), nullable=True),
        sa.Column("summary_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.bill_id"],
            name=op.f("fk_bill_summary_relation_bill_summary_relation_bill_id_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["bill_summaries.summary_id"],
            name=op.f(
                "fk_bill_summary_relation_bill_summary_relation_summary_id_bill_summaries"
            ),
        ),
        sa.PrimaryKeyConstraint("summary_id", name=op.f("pk_bill_summary_relation")),
    )
    op.create_table(
        "conf_summary_relation",
        sa.Column("conf_id", sa.Integer(), nullable=False),
        sa.Column("summary_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conf_id"],
            ["conferences.id"],
            name=op.f(
                "fk_conf_summary_relation_conf_summary_relation_conf_id_conferences"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["conf_summaries.id"],
            name=op.f(
                "fk_conf_summary_relation_conf_summary_relation_summary_id_conf_summaries"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "conf_id", "summary_id", name=op.f("pk_conf_summary_relation")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conf_summary_relation")
    op.drop_table("bill_summary_relation")
    op.drop_table("conf_summaries")
    op.drop_table("bill_summaries")
    op.drop_table("users")
    op.drop_table("user_interests")
    op.drop_table("similarity_scores")
    op.drop_table("role")
    op.drop_table("interests")
    op.drop_table("conferences")
    op.drop_table("bills")
    # ### end Alembic commands ###
