"""Auto-generated migration for feature/user-schema

Revision ID: f410c0a2aa17
Revises: 07e4900de360
Create Date: 2025-03-29 14:37:08.299362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'f410c0a2aa17'
down_revision: Union[str, None] = '07e4900de360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    # Calculate and set birthday based on age for existing users
    conn = op.get_bind()
    users = conn.execute(sa.text('SELECT id, age FROM users WHERE age IS NOT NULL')).fetchall()
    
    current_year = datetime.now().year
    
    for user in users:
        birth_year = current_year - user.age
        birthday = datetime(birth_year, 1, 1).date()  # Set to January 1st of birth year
        conn.execute(
            sa.text('UPDATE users SET birthday = :birthday WHERE id = :id'),
            {'birthday': birthday, 'id': user.id}
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
