"""Add DateChecker

Revision ID: f7be526e38ad
Revises: 300072a4706a
Create Date: 2025-03-12 22:05:18.691551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7be526e38ad'
down_revision: Union[str, None] = '300072a4706a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_checker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_date', sa.Date(), nullable=False),
    sa.Column('execute_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_date_checker'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_checker')
    # ### end Alembic commands ###
