"""empty message

Revision ID: fc71d0511e74
Revises: ca8a65ff8839
Create Date: 2025-03-03 20:59:19.677112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc71d0511e74"
down_revision: Union[str, None] = "ca8a65ff8839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills_embedding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bill_id", sa.String(length=255), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_embedding")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bills_embedding")
    # ### end Alembic commands ###
